# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de22b997025efb119baeadbc3dbad98559b188638e12ec0231f510064a6c3d19e74d2c4a9bcbcc754bc8a8d1b43e16436b66f11b42d10907894e765f1bd5e1c1

test:
  secret_key_base: a0c05066e7214eec9815a4cd794b22c08bf22a43fad2af3b491308cc47d70989a0dce2d0ea9aed50566f0c9aa44c6dc7df8b365e3cd6f63f972f7527a1c18b6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
